#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

count_number=0

while [ $count_number -lt 10 ]
do
  if [ $count_number -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count_number++ ))
done
