#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

list_directory=$(ls)
for index in $list_directory; do
  echo "$index" | cut -d '-' -f2
done
